### ISSUE TITLE
点击添加入站时没反应

### ISSUE THREAD

**Issue by ba573318** [FranzKafkaYu/x-ui#511]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

点击添加入站时没有反应，查看console显示如下：

### Version of x-ui

<details>

x-ui 0.3.4.4:20230717

</details>

### x-ui log or xray log

<details>
vue.min.js:6 ReferenceError: inModal is not defined
    at wn.openAddInbound (inbounds:397:21)
    at He (vue.min.js:6:11384)
    at a.n (vue.min.js:6:13168)
    at He (vue.min.js:6:11384)
    at e.$emit (vue.min.js:6:34373)
    at a.handleClick (antd.min.js:2:855525)
    at He (vue.min.js:6:11384)
    at HTMLButtonElement.n (vue.min.js:6:13168)
    at Yr.o._wrapper (vue.min.js:6:48505)
</details>

**Comment by FranzKafkaYu** [comment]
@ba573318 请修改浏览器语言为简体中文

**Comment by ba573318** [comment]
问题解决，感恩！
