### ISSUE TITLE
添加入站，报错了inModal is not defined

### ISSUE THREAD

**Issue by mrli834668690** [FranzKafkaYu/x-ui#561]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

添加入站，报错了inModal is not defined

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by jiangying000** [comment]
同样的错误


vue.min.js:6 ReferenceError: inModal is not defined
    at wn.openAddInbound (inbounds:399:21)
    at He (vue.min.js:6:11384)
    at a.n (vue.min.js:6:13168)
    at He (vue.min.js:6:11384)
    at e.$emit (vue.min.js:6:34373)
    at a.handleClick (antd.min.js:2:855525)
    at He (vue.min.js:6:11384)
    at HTMLButtonElement.n (vue.min.js:6:13168)
    at Yr.o._wrapper (vue.min.js:6:48505)
